"""Rule-layer vocabulary for product type normalization.

Strong material/form keywords are near-certain signals that may override the
LLM's choice (stage 4 of the pipeline). Synonyms map seller vocabulary onto
the canonical form/material words used in the Printway taxonomy names.
"""

# Seller word -> canonical material (matches taxonomy.material values)
MATERIAL_SYNONYMS: dict[str, str] = {
    "acrylic": "acrylic",
    "plexiglass": "acrylic",
    "lucite": "acrylic",
    "wood": "wood",
    "wooden": "wood",
    "bamboo": "wood",
    "walnut": "wood",
    "oak": "wood",
    "metal": "metal",
    "stainless": "metal",
    "steel": "metal",
    "aluminum": "metal",
    "brass": "metal",
    "silver": "metal",
    "gold": "metal",
    "ceramic": "ceramic",
    "porcelain": "ceramic",
    "glass": "glass",
    "crystal": "glass",
    "canvas": "canvas",
    "fabric": "fabric",
    "fleece": "fabric",
    "sherpa": "fabric",
    "cotton": "fabric",
    "polyester": "fabric",
    "coir": "fabric",
    "stone": "stone",
    "slate": "stone",
    "marble": "stone",
    "leather": "leather",
    "paper": "paper",
    "cardstock": "paper",
}

# Seller word/phrase -> canonical form word (the last noun of a taxonomy name)
FORM_SYNONYMS: dict[str, str] = {
    "ornament": "ornament",
    "bauble": "ornament",
    "xmas ball": "ornament",
    "tree decoration": "ornament",
    "suncatcher": "suncatcher",
    "sun catcher": "suncatcher",
    "tumbler": "tumbler",
    "travel cup": "tumbler",
    "mug": "mug",
    "coffee cup": "mug",
    "can glass": "glass",
    "beer glass": "glass",
    "pint glass": "glass",
    "cutting board": "board",
    "chopping board": "board",
    "charcuterie board": "board",
    "doormat": "doormat",
    "door mat": "doormat",
    "welcome mat": "doormat",
    "blanket": "blanket",
    "throw": "blanket",
    "canvas print": "print",
    "wall art": "print",
    "poster": "poster",
    "sign": "sign",
    "neon": "sign",
    "night light": "light",
    "nightlight": "light",
    "lamp": "light",
    "photo frame": "frame",
    "picture frame": "frame",
    "keychain": "keychain",
    "key chain": "keychain",
    "key ring": "keychain",
    "keyring": "keychain",
    "garden stone": "stone",
    "memorial stone": "stone",
    "stepping stone": "stone",
    "wind chime": "chime",
    "windchime": "chime",
    "garden flag": "flag",
    "house flag": "flag",
    "pet tag": "tag",
    "id tag": "tag",
    "dog tag": "tag",
    "tag": "tag",
    "bandana": "bandana",
    "pet bowl": "bowl",
    "dog bowl": "bowl",
    "cat bowl": "bowl",
    "t-shirt": "t-shirt",
    "tshirt": "t-shirt",
    "tee": "t-shirt",
    "shirt": "t-shirt",
    "hoodie": "hoodie",
    "sweatshirt": "hoodie",
    "tote": "bag",
    "tote bag": "bag",
    "pillow": "pillow",
    "cushion": "pillow",
    "plaque": "plaque",
    "award": "plaque",
    "trophy": "plaque",
    "car charm": "charm",
    "rearview mirror": "charm",
    "hanging charm": "charm",
    "necklace": "necklace",
    "pendant": "necklace",
    "bracelet": "bracelet",
    "wallet card": "card",
    "wallet insert": "card",
    "puzzle": "puzzle",
    "jigsaw": "puzzle",
    "mouse pad": "pad",
    "mousepad": "pad",
    "desk mat": "pad",
    "name plate": "plate",
    "nameplate": "plate",
    "desk sign": "plate",
}

# Marketing junk to strip before any matching
JUNK_PATTERNS = [
    "best gift",
    "gift idea",
    "free shipping",
    "unique",
    "perfect for",
    "sale",
    "2025",
    "2026",
    "keepsake",
]
